[UI]EVEREST-1005-Expand-divider-in-tabs-component changing the width …
percona/everest pull request #242
Opened 2024-04-26 11:49 UTC by X6uddy

Сhanged the width of the borderBottom

2024-04-26 11:59 UTC, dianabirs approved these changes

2024-05-03 06:59 UTC, solovevayaroslavna requested changes

2024-05-03 06:59 UTC, solovevayaroslavna commented on ui/apps/everest/src/pages/db-cluster-details/db-cluster-details.tsx
> -          width: 'fit-content',
it has to be done in all pages

2024-05-13 10:17 UTC, Daninda commented
Also expanded divider on the settings page

![image](https://github.com/percona/everest/assets/126169546/9f2f749b-7f92-4a43-b6f6-a126ddd96677)

2024-05-16 10:26 UTC, dianabirs approved these changes

2024-05-16 10:27 UTC, merged