EVEREST-1266-components-page-statuses: fix of components status
percona/everest pull request #645
Opened 2024-09-09 15:00 UTC by solovevayaroslavna

![image](https://github.com/user-attachments/assets/2c861541-d228-43df-91a6-97cc6b3d4bc1)

2024-09-10 09:40 UTC, recharte commented
@solovevayaroslavna I didn't review the code but looking at the screenshot in the PR's description it looks like you missed adding the boolean string to the ready column of the containers' rows. See the mock-up in [this ticket](https://perconadev.atlassian.net/browse/EVEREST-1268)

2024-09-10 09:42 UTC, recharte commented
Also the name of the container now should be under the name column and we should show the status of the container in the status column. Again this is the scope of https://perconadev.atlassian.net/browse/EVEREST-1268

2024-09-10 09:52 UTC, solovevayaroslavna commented
Thanks @recharte! I focused on the statuses, since the task description was about them, so I didn't notice🤦‍♀️ that some of the columns have an incorrect location, I'll fix it and double check it again, thanks again!

2024-09-10 09:55 UTC, recharte commented
> Thanks @recharte! I focused on the statuses, since the task description was about them, so I didn't notice🤦‍♀️ that some of the columns have an incorrect location, I'll fix it and double check it again, thanks again!

That's fine because you did focus on EVEREST-1266 and you successfully fixed it. I'm just letting you know that EVEREST-1268 is related and it details some more changes but it can be done in a separate PR.

2024-10-01 14:55 UTC, fabio-silva requested changes

2024-10-01 14:55 UTC, fabio-silva commented on ui/apps/everest/src/pages/db-cluster-details/components/components.constants.ts
> +  } else return COMPONENT_STATUS_TO_BASE_STATUS;
missing brackets

2024-10-02 07:37 UTC, dianabirs approved these changes

2024-10-02 10:53 UTC, fabio-silva approved these changes

2024-10-02 14:11 UTC, merged