EVEREST-1475 use type generation for API tests
percona/everest pull request #685
Opened 2024-09-17 09:19 UTC by yurkovychv

2024-09-17 11:33 UTC, recharte commented
Our Makefile has a [target (`gen`) ](https://github.com/percona/everest/blob/8642f65b75111397fe16f1f7fcb572e6362baa6f/Makefile#L48-L50) that among other things generates go files based on the openapi schema and then we have a step in our CI that runs `make gen` and [checks that we didn't miss committing any auto-generated files](https://github.com/percona/everest/blob/8642f65b75111397fe16f1f7fcb572e6362baa6f/.github/workflows/dev-be-ci.yaml#L86-L94).
We should probably add this generation of JS files from the openapi schema to the `gen` makefile target so that we don't forget to update the API tests files every time that we change the schema.

2024-09-17 19:00 UTC, recharte approved these changes

2024-09-18 09:00 UTC, oksana-grishchenko approved these changes

2024-09-18 09:20 UTC, tplavcic requested changes

2024-09-18 09:20 UTC, tplavcic commented on api-tests/support/types/database-clusters.ts
> +import { paths } from '@generatedTypes';
If I see correctly types from this file are currently not used?

2024-09-18 09:23 UTC, tplavcic commented on api-tests/support/types/database-clusters.ts
> +import { paths } from '@generatedTypes';
ok, let's leave it

2024-09-18 09:31 UTC, tplavcic commented on api-tests/support/types/database-engines.ts
> +export type DatabaseEnginesResponse = paths['/namespaces/{namespace}/database-engines']['get']['responses']['200']['content']['application/json'];
That was my initial thinking when I saw the naming yes, it would be good to have the consistent naming in all types.

2024-09-18 09:42 UTC, tplavcic approved these changes

2024-09-18 09:48 UTC, merged