EVEREST-1306: fix strings to numbers
percona/everest pull request #759
Opened 2024-10-11 09:55 UTC by solovevayaroslavna

possible improvement
This ticket is ready to merge, but it is better to wait for e2e tests for sharding to be sure that this change will not break anything https://github.com/percona/everest/pull/936

2024-10-24 11:47 UTC, fabio-silva requested changes

2024-10-24 11:47 UTC, fabio-silva commented on ui/apps/everest/src/components/cluster-form/resources/constants.ts
> +  } else return 7;
let's add brackets here

2024-12-16 11:26 UTC, dianabirs approved these changes

2024-12-19 11:19 UTC, fabio-silva approved these changes

2025-01-10 18:28 UTC, merged